image: docker:latest
stages:
  - deploy
  
deploy:
  stage: deploy    
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    # - eval $(ssh-agent -s)
    # - chmod 400 "$SSH_PRIVATE_KEY"
    # - ssh-add "$SSH_PRIVATE_KEY"
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    # 
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
    - sudo apt update && apt install openssh-server
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/fusion/project_em/books-store; git pull"
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/fusion/project_em/books-store; docker compose up -d"
