version: '3.9'
services:
  nginx:
    image: nginx:1.23.4
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./dev_ops-front/build:/usr/share/nginx/html
      - ./nginx/configs/conf.d:/etc/nginx/conf.d
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./dev_ops-back
    container_name: app-backend
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./dev_ops-back/src/:/app/backend
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  # frontend:
  #   build:
  #     context: ./dev_ops-front
  #     dockerfile: Dockerfile
  #   container_name: app-frontend
  #   volumes:
  #     - /app/node_modules
  #     - ./dev_ops-front/src/:/app/frontend
  #     - ./nginx/configs/conf.d:/etc/nginx/conf.d
  #     - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "fusiondb"
      POSTGRES_USER: "fusion"
      POSTGRES_PASSWORD: "fusion"
    ports:
      - "5433:5432"